version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 15
  ignore:
  - dependency-name: Moq
    versions:
    - 4.16.0
  - dependency-name: Unity
    versions:
    - 5.11.9
  - dependency-name: CommonServiceLocator
    versions:
    - 2.0.5
