//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReusableLibrary.Abstractions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReusableLibrary.Abstractions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already task running..
        /// </summary>
        internal static string AbstractBackgroundTaskAlreadyRunning {
            get {
                return ResourceManager.GetString("AbstractBackgroundTaskAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartIndex is out of bytes array.
        /// </summary>
        internal static string DecimalHelperOutOfRange {
            get {
                return ResourceManager.GetString("DecimalHelperOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too small bytes array range to convert it to decimal.
        /// </summary>
        internal static string DecimalHelperTooSmall {
            get {
                return ResourceManager.GetString("DecimalHelperTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache instance has been initialized already.
        /// </summary>
        internal static string ErrorCacheInitializedAlready {
            get {
                return ResourceManager.GetString("ErrorCacheInitializedAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DependencyResolver instance has been initialized already.
        /// </summary>
        internal static string ErrorDependencyResolverInitializedAlready {
            get {
                return ResourceManager.GetString("ErrorDependencyResolverInitializedAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ip address is not valid..
        /// </summary>
        internal static string ErrorInvalidIpAddress {
            get {
                return ResourceManager.GetString("ErrorInvalidIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Error Report Mail&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;font-family: Tahoma, Monospace; font-size: 8pt;&quot;&gt;
        ///        This message indicates that &lt;strong&gt;
        ///            &lt;%= ExceptionName%&gt;&lt;/strong&gt; occured in the
        ///        &lt;%= Application%&gt;
        ///        application. We apologize for the inconvenience. This error
        ///        has been automatically tracked in the operating system
        ///        event log. Please report this bug to th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ErrorReportMailBody {
            get {
                return ResourceManager.GetString("ErrorReportMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Error Report ({1}).
        /// </summary>
        internal static string ErrorReportMailSubject {
            get {
                return ResourceManager.GetString("ErrorReportMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation guard in {0} failed with error code {1}.
        /// </summary>
        internal static string ErrorRepositoryGuardAreaFailed {
            get {
                return ResourceManager.GetString("ErrorRepositoryGuardAreaFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation guard failed with error code {0}.
        /// </summary>
        internal static string ErrorRepositoryGuardFailed {
            get {
                return ResourceManager.GetString("ErrorRepositoryGuardFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for key &apos;{0}&apos;.
        /// </summary>
        internal static string NameValueCollectionHelperInvalidValue {
            get {
                return ResourceManager.GetString("NameValueCollectionHelperInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required value for key &apos;{0}&apos; is missing.
        /// </summary>
        internal static string NameValueCollectionHelperRequiredValue {
            get {
                return ResourceManager.GetString("NameValueCollectionHelperRequiredValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation has been timed out after performing {0} retries within {1}..
        /// </summary>
        internal static string RetryHelperTimeout {
            get {
                return ResourceManager.GetString("RetryHelperTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation has been timed out with no retry..
        /// </summary>
        internal static string RetryHelperTimeoutNoRetry {
            get {
                return ResourceManager.GetString("RetryHelperTimeoutNoRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninue key has not been initialized. Use Begin operation to initialize the key..
        /// </summary>
        internal static string RunOnceServiceKeyNotInitialized {
            get {
                return ResourceManager.GetString("RunOnceServiceKeyNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid option, use &apos;key = value;&apos;.
        /// </summary>
        internal static string StringOptionsInvalidOption {
            get {
                return ResourceManager.GetString("StringOptionsInvalidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout must be either non-negative and less than or equal to Int32.MaxValue or -1..
        /// </summary>
        internal static string TimeSpanTimeoutOutOfRange {
            get {
                return ResourceManager.GetString("TimeSpanTimeoutOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootstrapper.
        /// </summary>
        internal static string TraceSourceBootstrapper {
            get {
                return ResourceManager.GetString("TraceSourceBootstrapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EagerPool.
        /// </summary>
        internal static string TraceSourceEagerPool {
            get {
                return ResourceManager.GetString("TraceSourceEagerPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string TraceSourceError {
            get {
                return ResourceManager.GetString("TraceSourceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LazyPool.
        /// </summary>
        internal static string TraceSourceLazyPool {
            get {
                return ResourceManager.GetString("TraceSourceLazyPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManagedPool.
        /// </summary>
        internal static string TraceSourceManagedPool {
            get {
                return ResourceManager.GetString("TraceSourceManagedPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SynchronizedPool.
        /// </summary>
        internal static string TraceSourceSynchronizedPool {
            get {
                return ResourceManager.GetString("TraceSourceSynchronizedPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic.
        /// </summary>
        internal static string TraceSourceTopic {
            get {
                return ResourceManager.GetString("TraceSourceTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitPool.
        /// </summary>
        internal static string TraceSourceWaitPool {
            get {
                return ResourceManager.GetString("TraceSourceWaitPool", resourceCulture);
            }
        }
    }
}
